### ISSUE TITLE
Hitting rate limits on Github

### ISSUE THREAD

**Issue by philips** [philips/oncall-issue-filer#8]
```
$ kubectl -n k8s-security-bot logs oncall-issue-filer-1566579000-jrtml
panic: GET https://api.github.com/search/issues?q=repo:kubernetes-security%2Fsecurity-disclosures+527fbdf5-8650-44ea-81d0-5de1e7df3c2d-1566336573462&order=desc&page=1&per_page=1&sort=date: 403 API rate limit exceeded for user ID 44006949. [rate reset in 1m00s]

goroutine 1 [running]:
github.com/philips/oncall-issue-filer/cmd.ogMain()
        /go/src/github.com/philips/oncall-issue-filer/cmd/opsgenie.go:148 +0x522
github.com/philips/oncall-issue-filer/cmd.glob..func1(0xf4f2c0, 0xf756f0, 0x0, 0x0)
        /go/src/github.com/philips/oncall-issue-filer/cmd/opsgenie.go:36 +0x20
github.com/philips/oncall-issue-filer/vendor/github.com/spf13/cobra.(*Command).execute(0xf4f2c0, 0xf756f0, 0x0, 0x0, 0xf4f2c0, 0xf756f0)
        /go/src/github.com/philips/oncall-issue-filer/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/philips/oncall-issue-filer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf4f520, 0xc00000e148, 0x1, 0x1)
        /go/src/github.com/philips/oncall-issue-filer/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/philips/oncall-issue-filer/vendor/github.com/spf13/cobra.(*Command).Execute(0xf4f520, 0x407440, 0xc000068058)
        /go/src/github.com/philips/oncall-issue-filer/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/philips/oncall-issue-filer/cmd.Execute()
        /go/src/github.com/philips/oncall-issue-filer/cmd/root.go:90 +0x2d
main.main()
        /go/src/github.com/philips/oncall-issue-filer/main.go:20 +0x20
```

**Comment by philips** [comment]
Fixed via: https://github.com/philips/oncall-issue-filer/commit/110de7f848cc3b55d135598d0477deb6e87cb394
